### ISSUE TITLE
Unaccredited Fork

### ISSUE THREAD

**Issue by TheRagingWampa** [FxOxAxD/PUBG-ahk-helper#1]
I like a lot of the improvements you have made and I think this is a great fork but there is no denying that the base autofire part of the script was written by me. All I ask is to give me some credit in the description, and if I decide to use some of your improvements I will give you credit in the description and comments in the code.

**Comment by FxOxAxD** [comment]
As you can see, the description and readme its not yet finished, I'll write it soon when have time :D and you're credits will be there of course, but you're right :)

**Comment by TheRagingWampa** [comment]
If you'd like to speak with me, or maybe group up for this project you can reach me on discord https://discord.gg/CVaS8
