### ISSUE TITLE
I can only use squatting

### ISSUE THREAD

**Issue by 1019220756** [FxOxAxD/PUBG-ahk-helper#2]

**Comment by 1019220756** [comment]
Only itCrouch Jump

**Comment by FxOxAxD** [comment]
Please read the description, by default only C0rouchJump and Compensation is enabled, you have to toggle on modules:
You can change buttons.
ADS: Mouse Button 5
CrouchJump: NumPad 0
AutoFire: CapsLock
Compensation: NumPad Dot

Also remember in the last update there is a var called wantsRbeforeL which if this is enable you have to hold aim (right click) before shot (left click), you can disable it changing the value to 0.

Let me know if it worked for you.

**Comment by esc80** [comment]
hello) first of all - sorry, for my bad english and thank you for your helper
can you create a script for the first fast loot?

**Comment by FxOxAxD** [comment]
esc80 I don't really understand your request but please open a new Issue instead.
