### ISSUE TITLE
hello, big fan of you work. thought id share my features

### ISSUE THREAD

**Issue by aaeria** [FxOxAxD/PUBG-ahk-helper#3]
i stumbled upon your script awhile ago at an other website but they didnt give credit to the author. finally great to know who made this excellent helper. ive been using it ever since, made my own tweaks and features. maybe you could take them and polish them or whatever, since i picked up AHK with your script. im a real beginner, sorry in advance for all the messy codes.

anyway, you will undersatnd once u see the codes. i added stuff like strafing(still janky), for easier meanuever corners and lets your aim rest for potential enemy. quick scoping, spins, disable AF/comp while hold down a key(for grenades throws and honkings etc), crouch aiming, experimental anti spread. 

(making extended crouch jump option atm)

ill post again if u'd like once i come up with more ideas. here's the code:

https://pastebin.com/raw/3NJMB6A0

again.. big fan. thanks for making this! have a great day

**Comment by FxOxAxD** [comment]
Thanks for your words :)
I'll take a look at your code.
Greetings!
